const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const menu=$('.menu-btn'), nav=$('.nav-links'); menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)}); $$('.nav-links a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const theme=$('.theme-btn'); if(localStorage.getItem('theme')==='dark')document.body.classList.add('dark'); theme.textContent=document.body.classList.contains('dark')?'☀':'☾'; theme.addEventListener('click',()=>{document.body.classList.toggle('dark');const dark=document.body.classList.contains('dark');localStorage.setItem('theme',dark?'dark':'light');theme.textContent=dark?'☀':'☾'});
const sections=$$('main section[id]'), links=$$('.nav-links a'); const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){links.forEach(l=>l.classList.toggle('active',l.getAttribute('href')==='#'+e.target.id))}}),{rootMargin:'-30% 0px -60% 0px'}); sections.forEach(s=>io.observe(s));
const reveal=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');reveal.unobserve(e.target)}}),{threshold:.1}); $$('.reveal').forEach(x=>reveal.observe(x));
$$('.filter').forEach(btn=>btn.addEventListener('click',()=>{$$('.filter').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const f=btn.dataset.filter;$$('.project-card').forEach(c=>c.style.display=f==='all'||c.dataset.category.includes(f)?'block':'none')}));
const projectData={footstep:{eyebrow:'PROJECT 01 — ENERGY HARVESTING',title:'Footstep Power Generation Using Piezoelectric Sensors',html:`<p><strong>Objective:</strong> Explore the conversion of mechanical energy from footsteps into electrical energy using piezoelectric sensors.</p><p><strong>Concepts:</strong> Piezoelectric energy harvesting, PVDF, PZT, energy conversion, power management, sensor integration, Raspberry Pi, Python and COMSOL Multiphysics.</p><p><strong>Team roles:</strong> Mechanical and energy generation / energy harvester; power management and circuit design; Raspberry Pi and sensor integration; programming, monitoring and reporting.</p><p><strong>My role:</strong> <em>[ADD YOUR PERSONAL ROLE]</em></p><p><strong>Key results:</strong> <em>[ADD VERIFIED RESULTS — do not claim results here until available]</em></p><p><strong>Images:</strong> Add project photographs, COMSOL models and graphs to <code>images/projects/</code>.</p>`},comsol:{eyebrow:'PROJECT 02 — MODELLING',title:'Piezoelectric Materials in COMSOL Multiphysics',html:`<p>A simulation/modeling project involving piezoelectric materials and energy harvesting.</p><p><strong>Materials / concepts:</strong> PVDF, PZT-5H, aluminium substrate, piezoelectric effect, structural mechanics, electric potential, stress analysis, frequency response and mesh refinement.</p><p><strong>Results:</strong> <em>[ADD VERIFIED SIMULATION RESULTS]</em></p><p><strong>Model screenshots / graphs:</strong> Add them to <code>images/projects/</code> and duplicate the gallery markup in this modal if required.</p>`},academic:{eyebrow:'PROJECT 03 — ACADEMIC',title:'Academic & Laboratory Projects',html:`<p>Use this expandable entry to document additional verified work such as MATLAB/Simulink control-system experiments, state-space modelling, electrical circuits, transformer experiments, power electronics and digital electronics.</p><p><strong>Add:</strong> project title, objective, tools, your role, images and verified results.</p>`}};
const modal=$('#modal'); $$('.details-btn').forEach(b=>b.addEventListener('click',()=>{const d=projectData[b.dataset.project];$('#modalEyebrow').textContent=d.eyebrow;$('#modalTitle').textContent=d.title;$('#modalContent').innerHTML=d.html;modal.classList.add('open');modal.setAttribute('aria-hidden','false')})); $('.modal-close').addEventListener('click',closeModal); modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
const top=$('#topBtn');addEventListener('scroll',()=>top.classList.toggle('show',scrollY>500));top.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
$('#year').textContent=new Date().getFullYear();
$('#contactForm').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget,status=$('#formStatus');if(!f.checkValidity()){status.textContent='Please complete all fields with a valid email address.';f.reportValidity();return}status.textContent='Form validated. No email service is connected yet, so the message has not been sent. Connect Formspree, EmailJS or your own backend in script.js to enable delivery.';f.reset()});


